default: &defaults
   name: Admin User
   email: <%= ENV['ADMIN_EMAIL'] %>
   password: <%= ENV['ADMIN_PASSWORD'] %>

development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults


  admin_name:
  admin_email: admin@test.com
  admin_password: 1234567890