default: &defaults
   address: <%= ENV['SMTP_ADDRESS'] %>
   port: <%= ENV['SMTP_PORT'] %>
   domain: <%= ENV['SMTP_DOMAIN'] %>
   user_name: <%= ENV['SMTP_USER_NAME'] %>
   password: <%= ENV['SMTP_PASSWORD'] %>
   authentication: <%= ENV['SMTP_AUTHENTICATION'] || ':plain' %>
   enable_starttls_auto: <%= ENV['SMTP_ENABLE_STARTTTLS_AUTO'] || true %>

development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults